theme: minima
title: FormMasterPro
description: Transform Your Form-Filling Experience with AI-Powered Automation
author: FormMaster Team
baseurl: ""
url: ""

# Social links
github_username: haroldmei
twitter_username: formmaster

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
