name: Production Release

on:
  push:
    tags:
      - 'v*.*.*'  # Run when version tags are pushed
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-package:
    runs-on: windows-latest  # Changed to Windows for NSIS
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for git tags and commits
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build extension
        run: npm run build
      
      - name: Obfuscate code
        run: npm run obfuscate
      
      - name: Package extension
        run: node scripts/package.js
      
      - name: Get package name
        id: get-package
        run: |
          $packageName = Get-ChildItem -Path packages -Filter "form-master-pro-v*.zip" | Sort-Object -Property LastWriteTime -Descending | Select-Object -First 1 -ExpandProperty FullName
          echo "package=$packageName" >> $env:GITHUB_OUTPUT
          echo "filename=$(Split-Path -Leaf $packageName)" >> $env:GITHUB_OUTPUT
        shell: pwsh
      
      - name: Install NSIS
        run: |
          choco install nsis -y --version=3.08
          refreshenv
      
      - name: Build Windows installer
        run: npm run build:installer
      
      - name: Create GitHub Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.get-package.outputs.package }}
            FormMaster-Setup.exe
          name: FormMaster Pro ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.get-package.outputs.filename }}
          path: ${{ steps.get-package.outputs.package }}
          if-no-files-found: error
      
      - name: Upload installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: FormMaster-Setup.exe
          path: FormMaster-Setup.exe
          if-no-files-found: error
      
      - name: Package summary
        run: |
          echo "Package created: ${{ steps.get-package.outputs.filename }}"
          echo "Installer created: FormMaster-Setup.exe"
          echo "To publish to Chrome Web Store:"
          echo "1. Download the extension artifact from this workflow run"
          echo "2. Visit https://chrome.google.com/webstore/devconsole/"
          echo "3. Upload the ZIP file to update your extension"
