name: Production Release

on:
  push:
    tags:
      - 'v*.*.*'  # Run when version tags are pushed
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for git tags and commits
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build extension
        run: npm run build
      
      - name: Obfuscate code
        run: npm run obfuscate
      
      - name: Package extension
        run: node scripts/package.js
      
      - name: Get package name
        id: get-package
        run: |
          PACKAGE_NAME=$(find packages -name "form-master-pro-v*.zip" | sort -r | head -n 1)
          echo "::set-output name=package::$PACKAGE_NAME"
          echo "::set-output name=filename::$(basename $PACKAGE_NAME)"
      
      - name: Create GitHub Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.get-package.outputs.package }}
          name: FormMaster Pro ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.get-package.outputs.filename }}
          path: ${{ steps.get-package.outputs.package }}
          if-no-files-found: error
      
      - name: Package summary
        run: |
          echo "Package created: ${{ steps.get-package.outputs.filename }}"
          echo "To publish to Chrome Web Store:"
          echo "1. Download the artifact from this workflow run"
          echo "2. Visit https://chrome.google.com/webstore/devconsole/"
          echo "3. Upload the ZIP file to update your extension"
