name: Production Release

on:
  push:
    tags:
      - 'v*' # Run on version tags v1.0.0, v0.1.0, etc.

jobs:
  build_and_release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for change list generation

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build:prod

      - name: Package extension
        run: |
          cd dist
          zip -r ../formmaster-pro-${{ github.ref_name }}.zip *
          cd ..

      - name: Generate Change List
        id: changelog
        run: |
          # Find the previous tag to compare against
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          if [ -z "$PREV_TAG" ]; then
            # If no previous tag, use all commits
            echo "CHANGELOG<<EOF" >> $GITHUB_ENV
            echo "## 🚀 Initial Release" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "$(git log --pretty=format:"- %s" --no-merges)" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            # Generate changelog from previous tag
            echo "CHANGELOG<<EOF" >> $GITHUB_ENV
            echo "## 🚀 Changes since $PREV_TAG" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "$(git log --pretty=format:"- %s" --no-merges $PREV_TAG..HEAD)" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: FormMasterPro ${{ github.ref_name }}
          body: |
            # FormMasterPro ${{ github.ref_name }}
            
            ${{ env.CHANGELOG }}
            
            ## 📦 Installation
            
            1. Download the zip file below
            2. Unzip it to a folder on your computer
            3. Go to chrome://extensions/
            4. Enable "Developer mode"
            5. Click "Load unpacked" and select the unzipped folder
          files: formmaster-pro-${{ github.ref_name }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
